# Generated by Django 3.0.1 on 2019-12-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20191228_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
    ]
