# Generated by Django 3.0.1 on 2019-12-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20191229_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Order',
        ),
    ]
