# Generated by Django 3.0.1 on 2019-12-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20191229_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
