# Generated by Django 3.0.1 on 2019-12-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='txid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
