# Generated by Django 3.0.2 on 2020-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20191229_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='doc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='for_one_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
