# Generated by Django 3.0.2 on 2020-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20200508_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='doc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='for_one_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
    ]
