# Generated by Django 3.0.2 on 2020-05-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20200508_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_one_user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
